# -*- coding: utf-8 -*-
"""IPM06009_Anuj_Shivhare_ITA_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L12HWd3hjGZkfHz2Wnrw-yXHBa-272SW
"""

# AI-Based Judicial Case Prioritization & Duration Prediction
# Complete Google Colab Code
# Author: Anuj Shivhare | IPM06009
# ============================================================

# ─────────────────────────────────────────────────────────────
# CELL 1 — Install & Import Libraries
# ─────────────────────────────────────────────────────────────
# Run this cell first in Google Colab

!pip install -q openpyxl google-generativeai

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Sklearn - Preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score

# Sklearn - Supervised Classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.svm import SVC, SVR
from sklearn.neighbors import KNeighborsClassifier

# Sklearn - Supervised Regression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Sklearn - Unsupervised
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, confusion_matrix, classification_report,
                              mean_absolute_error, mean_squared_error, r2_score,
                              silhouette_score)

# Google Gemini AI
import google.generativeai as genai

print("=" * 60)
print("  All libraries imported successfully!")
print("=" * 60)


# ─────────────────────────────────────────────────────────────
# CELL 2 — Upload Dataset
# ─────────────────────────────────────────────────────────────
# Upload the judicial_case_dataset.xlsx file when prompted

from google.colab import files

print("Please upload the file: judicial_case_dataset.xlsx")
uploaded = files.upload()

df_raw = pd.read_excel('judicial_case_dataset.xlsx', sheet_name='Judicial_Case_Dataset')

print("\n✅ Dataset loaded successfully!")
print(f"   Shape: {df_raw.shape[0]} rows × {df_raw.shape[1]} columns")
print(f"\n{'─'*50}")
print("Column names:")
for col in df_raw.columns:
    print(f"   • {col}")


# ─────────────────────────────────────────────────────────────
# CELL 3 — Data Exploration (EDA)
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 1: EXPLORATORY DATA ANALYSIS")
print("=" * 60)

df = df_raw.copy()

print("\n📋 First 5 rows:")
print(df.head())

print(f"\n📊 Dataset Info:")
print(f"   Total records  : {len(df)}")
print(f"   Total features : {len(df.columns)}")
print(f"   Missing values : {df.isnull().sum().sum()}")
print(f"   Duplicates     : {df.duplicated().sum()}")

print(f"\n📈 Numeric Statistics:")
print(df.describe().round(2))

print(f"\n🎯 Target Variable — Priority_Level:")
print(df['Priority_Level'].value_counts())
print(f"\n⏱  Target Variable — Case_Age_Months:")
print(df['Case_Age_Months'].describe())

print(f"\n📂 Categorical Distributions:")
for col in ['Case_Type', 'Court_Level', 'Case_Status', 'Case_Category']:
    print(f"\n  {col}:")
    print(df[col].value_counts().to_string())


# ─────────────────────────────────────────────────────────────
# CELL 4 — EDA Visualizations
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 1: EDA VISUALIZATIONS")
print("=" * 60)

colors_priority = {'High': '#E24B4A', 'Medium': '#EF9F27', 'Low': '#1D9E75'}
palette = ['#185FA5', '#1D9E75', '#E24B4A', '#EF9F27', '#7F77DD', '#D85A30', '#639922', '#BA7517']

fig, axes = plt.subplots(3, 3, figsize=(18, 15))
fig.suptitle('Judicial Case Dataset — Exploratory Data Analysis',
             fontsize=16, fontweight='bold', y=0.98)

# 1. Priority Level Distribution
ax = axes[0, 0]
priority_counts = df['Priority_Level'].value_counts()
bars = ax.bar(priority_counts.index, priority_counts.values,
              color=[colors_priority[x] for x in priority_counts.index], edgecolor='white', linewidth=1.5)
ax.set_title('Priority Level Distribution', fontweight='bold')
ax.set_xlabel('Priority Level')
ax.set_ylabel('Number of Cases')
for bar, val in zip(bars, priority_counts.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 8,
            str(val), ha='center', fontweight='bold', fontsize=11)
ax.set_ylim(0, max(priority_counts.values) * 1.15)

# 2. Case Type Distribution
ax = axes[0, 1]
type_counts = df['Case_Type'].value_counts()
wedges, texts, autotexts = ax.pie(type_counts.values, labels=type_counts.index,
                                   autopct='%1.1f%%', colors=['#185FA5', '#E24B4A'],
                                   startangle=90, textprops={'fontsize': 12})
for autotext in autotexts:
    autotext.set_fontweight('bold')
ax.set_title('Case Type Distribution', fontweight='bold')

# 3. Case Status Distribution
ax = axes[0, 2]
status_counts = df['Case_Status'].value_counts()
bars = ax.bar(status_counts.index, status_counts.values,
              color=['#E24B4A', '#1D9E75'], edgecolor='white', linewidth=1.5)
ax.set_title('Case Status Distribution', fontweight='bold')
ax.set_xlabel('Case Status')
ax.set_ylabel('Number of Cases')
for bar, val in zip(bars, status_counts.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
            str(val), ha='center', fontweight='bold', fontsize=12)
ax.set_ylim(0, max(status_counts.values) * 1.15)

# 4. Case Age Distribution
ax = axes[1, 0]
ax.hist(df['Case_Age_Months'], bins=30, color='#185FA5', edgecolor='white',
        linewidth=0.8, alpha=0.85)
ax.axvline(df['Case_Age_Months'].mean(), color='#E24B4A', linestyle='--',
           linewidth=2, label=f"Mean: {df['Case_Age_Months'].mean():.1f} months")
ax.set_title('Case Age Distribution', fontweight='bold')
ax.set_xlabel('Case Age (Months)')
ax.set_ylabel('Frequency')
ax.legend()

# 5. Hearings by Priority
ax = axes[1, 1]
for priority, color in colors_priority.items():
    data = df[df['Priority_Level'] == priority]['Number_of_Hearings']
    ax.hist(data, bins=20, alpha=0.65, label=priority, color=color, edgecolor='white')
ax.set_title('Hearings Distribution by Priority', fontweight='bold')
ax.set_xlabel('Number of Hearings')
ax.set_ylabel('Frequency')
ax.legend()

# 6. Court Level Distribution
ax = axes[1, 2]
court_counts = df['Court_Level'].value_counts()
ax.barh(court_counts.index, court_counts.values, color=palette[:len(court_counts)],
        edgecolor='white', linewidth=1.2)
ax.set_title('Court Level Distribution', fontweight='bold')
ax.set_xlabel('Number of Cases')
for i, val in enumerate(court_counts.values):
    ax.text(val + 3, i, str(val), va='center', fontweight='bold')

# 7. Case Age by Priority (Box Plot)
ax = axes[2, 0]
priority_order = ['Low', 'Medium', 'High']
data_grouped = [df[df['Priority_Level'] == p]['Case_Age_Months'].values for p in priority_order]
bp = ax.boxplot(data_grouped, labels=priority_order, patch_artist=True)
for patch, priority in zip(bp['boxes'], priority_order):
    patch.set_facecolor(colors_priority[priority])
    patch.set_alpha(0.75)
ax.set_title('Case Age by Priority Level', fontweight='bold')
ax.set_xlabel('Priority Level')
ax.set_ylabel('Case Age (Months)')

# 8. Top Case Categories
ax = axes[2, 1]
cat_counts = df['Case_Category'].value_counts().head(8)
ax.barh(cat_counts.index, cat_counts.values, color=palette[:len(cat_counts)],
        edgecolor='white', linewidth=1.2)
ax.set_title('Top Case Categories', fontweight='bold')
ax.set_xlabel('Number of Cases')
for i, val in enumerate(cat_counts.values):
    ax.text(val + 1, i, str(val), va='center', fontsize=10)

# 9. Hearings vs Case Age Scatter
ax = axes[2, 2]
for priority, color in colors_priority.items():
    mask = df['Priority_Level'] == priority
    ax.scatter(df.loc[mask, 'Number_of_Hearings'],
               df.loc[mask, 'Case_Age_Months'],
               c=color, label=priority, alpha=0.5, s=20, edgecolors='none')
ax.set_title('Hearings vs Case Age', fontweight='bold')
ax.set_xlabel('Number of Hearings')
ax.set_ylabel('Case Age (Months)')
ax.legend(title='Priority')

plt.tight_layout()
plt.savefig('eda_visualizations.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ EDA plot saved as 'eda_visualizations.png'")


# ─────────────────────────────────────────────────────────────
# CELL 5 — Feature Engineering & Preprocessing
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 2: FEATURE ENGINEERING & PREPROCESSING")
print("=" * 60)

df_ml = df.copy()

# --- New derived features ---
df_ml['Adjournment_Rate']   = df_ml['Number_of_Adjournments'] / (df_ml['Number_of_Hearings'] + 1)
df_ml['Hearing_Age_Ratio']  = df_ml['Number_of_Hearings'] / (df_ml['Case_Age_Months'] + 1)
df_ml['Is_Criminal']        = (df_ml['Case_Type'] == 'Criminal').astype(int)
df_ml['Is_Pending']         = (df_ml['Case_Status'] == 'Pending').astype(int)
df_ml['Age_Category']       = pd.cut(df_ml['Case_Age_Months'],
                                      bins=[0, 12, 36, 72, 1000],
                                      labels=[0, 1, 2, 3]).astype(int)

print("✅ New features created:")
print("   • Adjournment_Rate   = adjournments / (hearings + 1)")
print("   • Hearing_Age_Ratio  = hearings / (case_age + 1)")
print("   • Is_Criminal        = 1 if Criminal, else 0")
print("   • Is_Pending         = 1 if Pending, else 0")
print("   • Age_Category       = Binned case age (0-3)")

# --- Encode categorical columns ---
le_dict = {}
cat_cols = ['Case_Type', 'Case_Category', 'Court_Level', 'State', 'Case_Status', 'Priority_Level']
for col in cat_cols:
    le = LabelEncoder()
    df_ml[col + '_enc'] = le.fit_transform(df_ml[col])
    le_dict[col] = le

print("\n✅ Label encoding done for:", cat_cols)

# --- Feature set for models ---
FEATURES = [
    'Case_Type_enc', 'Case_Category_enc', 'Court_Level_enc', 'State_enc',
    'Year_Filed', 'Number_of_Hearings', 'Number_of_Adjournments',
    'Number_of_Parties', 'Judge_Changes', 'Is_Criminal', 'Is_Pending',
    'Adjournment_Rate', 'Hearing_Age_Ratio', 'Age_Category'
]

TARGET_CLASS = 'Priority_Level_enc'   # For classification
TARGET_REG   = 'Case_Age_Months'      # For regression

X = df_ml[FEATURES]
y_class = df_ml[TARGET_CLASS]
y_reg   = df_ml[TARGET_REG]

# --- Correlation Heatmap ---
fig, axes = plt.subplots(1, 2, figsize=(20, 8))

# Numeric correlation
numeric_cols = ['Number_of_Hearings', 'Number_of_Adjournments', 'Number_of_Parties',
                'Judge_Changes', 'Case_Age_Months', 'Adjournment_Rate',
                'Hearing_Age_Ratio', 'Is_Criminal', 'Is_Pending', 'Year_Filed']
corr_matrix = df_ml[numeric_cols].corr()
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True, linewidths=0.5, ax=axes[0],
            cbar_kws={"shrink": 0.8}, annot_kws={"size": 8})
axes[0].set_title('Feature Correlation Matrix', fontweight='bold', fontsize=13)
axes[0].tick_params(axis='x', rotation=45)

# Priority vs features bar
priority_means = df_ml.groupby('Priority_Level')[
    ['Number_of_Hearings', 'Case_Age_Months', 'Judge_Changes', 'Adjournment_Rate']
].mean()
priority_means_normalized = (priority_means - priority_means.min()) / (priority_means.max() - priority_means.min())
priority_means_normalized.T.plot(kind='bar', ax=axes[1],
                                  color=[colors_priority[p] for p in priority_means_normalized.index],
                                  edgecolor='white', linewidth=0.8)
axes[1].set_title('Normalized Feature Means by Priority Level', fontweight='bold', fontsize=13)
axes[1].set_xlabel('Features')
axes[1].set_ylabel('Normalized Mean Value')
axes[1].tick_params(axis='x', rotation=30)
axes[1].legend(title='Priority Level')

plt.tight_layout()
plt.savefig('feature_engineering.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ Feature engineering plot saved as 'feature_engineering.png'")

# --- Scale features ---
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# --- Train/Test Split ---
X_train, X_test, yc_train, yc_test = train_test_split(X_scaled, y_class, test_size=0.2, random_state=42, stratify=y_class)
_, _, yr_train, yr_test            = train_test_split(X_scaled, y_reg,   test_size=0.2, random_state=42)

print(f"\n✅ Train/Test split complete:")
print(f"   Training set : {X_train.shape[0]} samples")
print(f"   Test set     : {X_test.shape[0]} samples")
print(f"   Features     : {X_train.shape[1]}")


# ─────────────────────────────────────────────────────────────
# CELL 6 — SUPERVISED: Classification Models
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 3a: SUPERVISED LEARNING — CLASSIFICATION")
print("  Target: Priority Level (Low / Medium / High)")
print("=" * 60)

label_names = le_dict['Priority_Level'].classes_

classifiers = {
    'Decision Tree'  : DecisionTreeClassifier(max_depth=8, random_state=42),
    'Random Forest'  : RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42),
    'SVM'            : SVC(kernel='rbf', C=1.5, gamma='scale', probability=True, random_state=42),
    'KNN'            : KNeighborsClassifier(n_neighbors=7, metric='euclidean')
}

clf_results = {}
clf_models  = {}

for name, model in classifiers.items():
    print(f"\n  Training {name}...")
    model.fit(X_train, yc_train)
    y_pred = model.predict(X_test)

    acc  = accuracy_score(yc_test, y_pred)
    prec = precision_score(yc_test, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(yc_test, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(yc_test, y_pred, average='weighted', zero_division=0)
    cv   = cross_val_score(model, X_scaled, y_class, cv=5, scoring='accuracy').mean()

    clf_results[name] = {'Accuracy': acc, 'Precision': prec,
                         'Recall': rec, 'F1 Score': f1, 'CV Score': cv}
    clf_models[name]  = (model, y_pred)

    print(f"    ✅ Accuracy: {acc:.4f} | F1: {f1:.4f} | CV: {cv:.4f}")

# Print comparison table
print(f"\n{'─'*65}")
print(f"  {'Model':<18} {'Accuracy':>9} {'Precision':>10} {'Recall':>8} {'F1':>8} {'CV':>8}")
print(f"{'─'*65}")
for name, res in clf_results.items():
    print(f"  {name:<18} {res['Accuracy']:>9.4f} {res['Precision']:>10.4f} "
          f"{res['Recall']:>8.4f} {res['F1 Score']:>8.4f} {res['CV Score']:>8.4f}")
print(f"{'─'*65}")

best_clf = max(clf_results, key=lambda x: clf_results[x]['F1 Score'])
print(f"\n  🏆 Best Classifier: {best_clf} (F1 = {clf_results[best_clf]['F1 Score']:.4f})")


# ─────────────────────────────────────────────────────────────
# CELL 7 — Classification Visualizations
# ─────────────────────────────────────────────────────────────

fig, axes = plt.subplots(2, 3, figsize=(20, 12))
fig.suptitle('Supervised Learning — Classification Results', fontsize=15, fontweight='bold')

# 1. Model Comparison Bar Chart
ax = axes[0, 0]
metrics  = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
x        = np.arange(len(metrics))
width    = 0.2
model_colors = ['#185FA5', '#1D9E75', '#E24B4A', '#EF9F27']
for i, (name, res) in enumerate(clf_results.items()):
    vals = [res[m] for m in metrics]
    bars = ax.bar(x + i*width, vals, width, label=name,
                  color=model_colors[i], alpha=0.85, edgecolor='white')
ax.set_title('Model Performance Comparison', fontweight='bold')
ax.set_xticks(x + width*1.5)
ax.set_xticklabels(metrics)
ax.set_ylim(0, 1.15)
ax.set_ylabel('Score')
ax.legend(fontsize=9)
ax.axhline(y=0.8, color='gray', linestyle='--', linewidth=0.8, alpha=0.6)

# 2-5. Confusion Matrices
for idx, (name, (model, y_pred)) in enumerate(clf_models.items()):
    row, col = divmod(idx + 1, 3)
    ax = axes[row, col]
    cm = confusion_matrix(yc_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_names, yticklabels=label_names,
                linewidths=0.5, ax=ax, cbar=False,
                annot_kws={"size": 12, "weight": "bold"})
    ax.set_title(f'Confusion Matrix — {name}', fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')

# 6. CV Score Comparison
ax = axes[1, 2]
names = list(clf_results.keys())
cv_scores = [clf_results[n]['CV Score'] for n in names]
bars = ax.barh(names, cv_scores, color=model_colors, edgecolor='white', linewidth=1.2)
ax.set_title('Cross-Validation Scores (5-Fold)', fontweight='bold')
ax.set_xlabel('CV Accuracy')
ax.set_xlim(0, 1.1)
for bar, val in zip(bars, cv_scores):
    ax.text(val + 0.01, bar.get_y() + bar.get_height()/2,
            f'{val:.4f}', va='center', fontweight='bold')
ax.axvline(x=0.8, color='gray', linestyle='--', linewidth=0.8, alpha=0.6)

plt.tight_layout()
plt.savefig('classification_results.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Classification results saved as 'classification_results.png'")

# Best model detailed report
print(f"\n{'='*60}")
print(f"  Detailed Report — {best_clf}")
print(f"{'='*60}")
best_model, best_pred = clf_models[best_clf]
print(classification_report(yc_test, best_pred, target_names=label_names))


# ─────────────────────────────────────────────────────────────
# CELL 8 — SUPERVISED: Regression Models
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 3a: SUPERVISED LEARNING — REGRESSION")
print("  Target: Case Duration (Months)")
print("=" * 60)

regressors = {
    'Linear Regression'      : LinearRegression(),
    'Random Forest Regressor': RandomForestRegressor(n_estimators=150, max_depth=10, random_state=42),
    'SVR'                    : SVR(kernel='rbf', C=10, gamma='scale', epsilon=0.1)
}

reg_results = {}
reg_models  = {}

for name, model in regressors.items():
    print(f"\n  Training {name}...")
    model.fit(X_train, yr_train)
    y_pred = model.predict(X_test)

    mae  = mean_absolute_error(yr_test, y_pred)
    rmse = np.sqrt(mean_squared_error(yr_test, y_pred))
    r2   = r2_score(yr_test, y_pred)

    reg_results[name] = {'MAE': mae, 'RMSE': rmse, 'R² Score': r2}
    reg_models[name]  = (model, y_pred)

    print(f"    ✅ MAE: {mae:.2f} | RMSE: {rmse:.2f} | R²: {r2:.4f}")

print(f"\n{'─'*52}")
print(f"  {'Model':<28} {'MAE':>7} {'RMSE':>8} {'R²':>8}")
print(f"{'─'*52}")
for name, res in reg_results.items():
    print(f"  {name:<28} {res['MAE']:>7.2f} {res['RMSE']:>8.2f} {res['R² Score']:>8.4f}")
print(f"{'─'*52}")

best_reg = max(reg_results, key=lambda x: reg_results[x]['R² Score'])
print(f"\n  🏆 Best Regressor: {best_reg} (R² = {reg_results[best_reg]['R² Score']:.4f})")


# ─────────────────────────────────────────────────────────────
# CELL 9 — Regression Visualizations
# ─────────────────────────────────────────────────────────────

fig, axes = plt.subplots(2, 3, figsize=(20, 12))
fig.suptitle('Supervised Learning — Regression Results', fontsize=15, fontweight='bold')

reg_colors = ['#185FA5', '#1D9E75', '#E24B4A']

# 1. MAE / RMSE Comparison
ax = axes[0, 0]
names  = list(reg_results.keys())
mae_v  = [reg_results[n]['MAE']  for n in names]
rmse_v = [reg_results[n]['RMSE'] for n in names]
x      = np.arange(len(names))
ax.bar(x - 0.2, mae_v,  0.35, label='MAE',  color='#185FA5', edgecolor='white')
ax.bar(x + 0.2, rmse_v, 0.35, label='RMSE', color='#E24B4A', edgecolor='white')
ax.set_title('MAE & RMSE Comparison', fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(['Lin. Reg', 'RF Reg', 'SVR'], fontsize=10)
ax.set_ylabel('Error (Months)')
ax.legend()

# 2. R² Score Comparison
ax = axes[0, 1]
r2_v = [reg_results[n]['R² Score'] for n in names]
bars = ax.bar(names, r2_v, color=reg_colors, edgecolor='white', linewidth=1.5)
ax.set_title('R² Score Comparison', fontweight='bold')
ax.set_ylabel('R² Score')
ax.set_ylim(0, 1.1)
ax.set_xticklabels(['Lin. Reg', 'RF Reg', 'SVR'])
for bar, val in zip(bars, r2_v):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f'{val:.4f}', ha='center', fontweight='bold')
ax.axhline(y=0.7, color='gray', linestyle='--', linewidth=0.8, alpha=0.6)

# 3–5. Actual vs Predicted + Residuals
for idx, (name, (model, y_pred)) in enumerate(reg_models.items()):
    row = idx // 3 + (0 if idx < 1 else 1)
    col = idx % 3 if idx > 0 else 2

    ax = axes[row, col]
    ax.scatter(yr_test, y_pred, alpha=0.45, s=18,
               color=reg_colors[idx], edgecolors='none')
    min_v, max_v = min(yr_test.min(), y_pred.min()), max(yr_test.max(), y_pred.max())
    ax.plot([min_v, max_v], [min_v, max_v], 'k--', linewidth=1.5, label='Perfect fit')
    ax.set_title(f'Actual vs Predicted — {name}', fontweight='bold', fontsize=10)
    ax.set_xlabel('Actual (Months)')
    ax.set_ylabel('Predicted (Months)')
    ax.legend(fontsize=9)

# Residual plot for best model
ax = axes[1, 0]
_, best_reg_pred = reg_models[best_reg]
residuals = yr_test.values - best_reg_pred
ax.scatter(best_reg_pred, residuals, alpha=0.45, s=18,
           color='#7F77DD', edgecolors='none')
ax.axhline(y=0, color='red', linestyle='--', linewidth=1.5)
ax.set_title(f'Residual Plot — {best_reg}', fontweight='bold', fontsize=10)
ax.set_xlabel('Predicted (Months)')
ax.set_ylabel('Residuals')

# Feature Importance from RF Regressor
ax = axes[1, 1]
rf_reg_model = reg_models['Random Forest Regressor'][0]
importances  = rf_reg_model.feature_importances_
feat_imp_df  = pd.DataFrame({'Feature': FEATURES, 'Importance': importances})
feat_imp_df  = feat_imp_df.sort_values('Importance', ascending=True).tail(10)
ax.barh(feat_imp_df['Feature'], feat_imp_df['Importance'],
        color='#1D9E75', edgecolor='white')
ax.set_title('Feature Importances (RF Regressor)', fontweight='bold', fontsize=10)
ax.set_xlabel('Importance Score')

plt.tight_layout()
plt.savefig('regression_results.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Regression results saved as 'regression_results.png'")


# ─────────────────────────────────────────────────────────────
# CELL 10 — UNSUPERVISED: K-Means Clustering
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 3b: UNSUPERVISED LEARNING — K-MEANS CLUSTERING")
print("=" * 60)

# Elbow method
inertias    = []
sil_scores  = []
K_range     = range(2, 11)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)
    sil_scores.append(silhouette_score(X_scaled, km.labels_))

# Best K by silhouette
best_k = K_range[np.argmax(sil_scores)]
print(f"  ✅ Optimal K (by Silhouette Score): {best_k}")
print(f"     Best Silhouette Score: {max(sil_scores):.4f}")

# Fit final model
kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
df_ml['Cluster'] = kmeans.fit_predict(X_scaled)

# Cluster summary
print(f"\n  Cluster Distribution:")
cluster_summary = df_ml.groupby('Cluster').agg(
    Count=('Case_ID', 'count'),
    Avg_Age=('Case_Age_Months', 'mean'),
    Avg_Hearings=('Number_of_Hearings', 'mean'),
    Priority_High=('Priority_Level', lambda x: (x=='High').sum()),
    Pending_Count=('Case_Status', lambda x: (x=='Pending').sum())
).round(2)
print(cluster_summary)


# ─────────────────────────────────────────────────────────────
# CELL 11 — UNSUPERVISED: PCA + Anomaly Detection
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 3b: PCA + ANOMALY DETECTION")
print("=" * 60)

# PCA
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)
df_ml['PCA1'] = X_pca[:, 0]
df_ml['PCA2'] = X_pca[:, 1]
explained = pca.explained_variance_ratio_
print(f"  ✅ PCA Explained Variance: PC1={explained[0]:.3f} | PC2={explained[1]:.3f} | Total={sum(explained):.3f}")

# Isolation Forest — Anomaly Detection
iso = IsolationForest(contamination=0.05, random_state=42)
df_ml['Anomaly_Score'] = iso.fit_predict(X_scaled)
df_ml['Is_Anomaly']    = (df_ml['Anomaly_Score'] == -1).astype(int)
n_anomalies = df_ml['Is_Anomaly'].sum()
print(f"  ✅ Anomaly Detection: {n_anomalies} unusual cases detected ({n_anomalies/len(df_ml)*100:.1f}%)")

# --- Unsupervised Visualizations ---
fig, axes = plt.subplots(2, 3, figsize=(20, 12))
fig.suptitle('Unsupervised Learning — Clustering, PCA & Anomaly Detection',
             fontsize=15, fontweight='bold')

cluster_colors = ['#185FA5', '#1D9E75', '#E24B4A', '#EF9F27', '#7F77DD', '#D85A30']

# 1. Elbow Curve
ax = axes[0, 0]
ax.plot(list(K_range), inertias, 'bo-', linewidth=2, markersize=7, markerfacecolor='#E24B4A')
ax.axvline(x=best_k, color='#E24B4A', linestyle='--', linewidth=2,
           label=f'Best K={best_k}')
ax.set_title('Elbow Method — Optimal K', fontweight='bold')
ax.set_xlabel('Number of Clusters (K)')
ax.set_ylabel('Inertia')
ax.legend()

# 2. Silhouette Scores
ax = axes[0, 1]
ax.plot(list(K_range), sil_scores, 'gs-', linewidth=2, markersize=7, markerfacecolor='#185FA5')
ax.axvline(x=best_k, color='#E24B4A', linestyle='--', linewidth=2,
           label=f'Best K={best_k}')
ax.set_title('Silhouette Scores by K', fontweight='bold')
ax.set_xlabel('Number of Clusters (K)')
ax.set_ylabel('Silhouette Score')
ax.legend()

# 3. PCA Scatter — Colored by Cluster
ax = axes[0, 2]
for c in range(best_k):
    mask = df_ml['Cluster'] == c
    ax.scatter(df_ml.loc[mask, 'PCA1'], df_ml.loc[mask, 'PCA2'],
               s=25, alpha=0.65, color=cluster_colors[c % len(cluster_colors)],
               label=f'Cluster {c}', edgecolors='none')
ax.set_title('PCA Scatter — K-Means Clusters', fontweight='bold')
ax.set_xlabel(f'PC1 ({explained[0]*100:.1f}% variance)')
ax.set_ylabel(f'PC2 ({explained[1]*100:.1f}% variance)')
ax.legend(fontsize=9)

# 4. PCA Scatter — Colored by Priority
ax = axes[1, 0]
for priority, color in colors_priority.items():
    mask = df_ml['Priority_Level'] == priority
    ax.scatter(df_ml.loc[mask, 'PCA1'], df_ml.loc[mask, 'PCA2'],
               s=25, alpha=0.65, color=color, label=priority, edgecolors='none')
ax.set_title('PCA Scatter — Priority Level', fontweight='bold')
ax.set_xlabel(f'PC1 ({explained[0]*100:.1f}%)')
ax.set_ylabel(f'PC2 ({explained[1]*100:.1f}%)')
ax.legend(title='Priority')

# 5. Anomaly Detection Scatter
ax = axes[1, 1]
normal_mask  = df_ml['Is_Anomaly'] == 0
anomaly_mask = df_ml['Is_Anomaly'] == 1
ax.scatter(df_ml.loc[normal_mask, 'PCA1'],  df_ml.loc[normal_mask, 'PCA2'],
           s=20, alpha=0.5, color='#185FA5', label='Normal', edgecolors='none')
ax.scatter(df_ml.loc[anomaly_mask, 'PCA1'], df_ml.loc[anomaly_mask, 'PCA2'],
           s=60, alpha=0.9, color='#E24B4A', label=f'Anomaly ({n_anomalies})',
           marker='X', edgecolors='#8B0000', linewidths=0.5)
ax.set_title('Anomaly Detection (Isolation Forest)', fontweight='bold')
ax.set_xlabel('PC1')
ax.set_ylabel('PC2')
ax.legend()

# 6. Cluster Profile Heatmap
ax = axes[1, 2]
cluster_profile = df_ml.groupby('Cluster')[
    ['Case_Age_Months', 'Number_of_Hearings', 'Number_of_Adjournments',
     'Judge_Changes', 'Adjournment_Rate']
].mean()
cluster_profile_norm = (cluster_profile - cluster_profile.min()) / \
                       (cluster_profile.max() - cluster_profile.min())
sns.heatmap(cluster_profile_norm, annot=True, fmt='.2f', cmap='YlOrRd',
            linewidths=0.5, ax=ax, cbar_kws={"shrink": 0.8},
            annot_kws={"size": 9, "weight": "bold"})
ax.set_title('Cluster Profile Heatmap (Normalized)', fontweight='bold')
ax.set_xlabel('Features')
ax.set_ylabel('Cluster')

plt.tight_layout()
plt.savefig('unsupervised_results.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Unsupervised results saved as 'unsupervised_results.png'")


# ─────────────────────────────────────────────────────────────
# CELL 12 — Final Prediction System
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 4: PREDICTION SYSTEM — NEW CASE INPUT")
print("=" * 60)

def predict_new_case(case_type, case_category, court_level, state,
                     year_filed, num_hearings, num_adjournments,
                     num_parties, judge_changes, case_status):
    """
    Predict Priority Level and Case Duration for a new case.
    """
    # Encode inputs
    def safe_encode(le, val):
        if val in le.classes_:
            return le.transform([val])[0]
        return 0  # default if unseen

    ct_enc  = safe_encode(le_dict['Case_Type'],      case_type)
    cc_enc  = safe_encode(le_dict['Case_Category'],  case_category)
    cl_enc  = safe_encode(le_dict['Court_Level'],    court_level)
    st_enc  = safe_encode(le_dict['State'],          state)
    cs_enc  = safe_encode(le_dict['Case_Status'],    case_status)

    # Derived features
    adj_rate   = num_adjournments / (num_hearings + 1)
    hear_ratio = num_hearings / 25  # normalizing proxy
    is_crim    = 1 if case_type == 'Criminal' else 0
    is_pend    = 1 if case_status == 'Pending' else 0
    age_est    = min((2024 - year_filed) * 12, 240)
    age_cat    = 0 if age_est <= 12 else (1 if age_est <= 36 else (2 if age_est <= 72 else 3))

    input_vec = np.array([[ct_enc, cc_enc, cl_enc, st_enc, year_filed,
                           num_hearings, num_adjournments, num_parties,
                           judge_changes, is_crim, is_pend,
                           adj_rate, hear_ratio, age_cat]])
    input_scaled = scaler.transform(input_vec)

    # Predictions
    best_clf_model = clf_models[best_clf][0]
    priority_enc   = best_clf_model.predict(input_scaled)[0]
    priority_label = le_dict['Priority_Level'].inverse_transform([priority_enc])[0]

    best_reg_model = reg_models[best_reg][0]
    duration_pred  = max(1, best_reg_model.predict(input_scaled)[0])

    return priority_label, round(duration_pred, 1)


# ── Test predictions ──
test_cases = [
    {
        'case_type': 'Criminal', 'case_category': 'Murder',
        'court_level': 'High Court', 'state': 'Maharashtra',
        'year_filed': 2018, 'num_hearings': 22, 'num_adjournments': 14,
        'num_parties': 4, 'judge_changes': 2, 'case_status': 'Pending'
    },
    {
        'case_type': 'Civil', 'case_category': 'Property Dispute',
        'court_level': 'District Court', 'state': 'Delhi',
        'year_filed': 2020, 'num_hearings': 8, 'num_adjournments': 3,
        'num_parties': 2, 'judge_changes': 0, 'case_status': 'Pending'
    },
    {
        'case_type': 'Criminal', 'case_category': 'Cybercrime',
        'court_level': 'Sessions Court', 'state': 'Karnataka',
        'year_filed': 2022, 'num_hearings': 4, 'num_adjournments': 1,
        'num_parties': 3, 'judge_changes': 0, 'case_status': 'Pending'
    }
]

print("\n  Sample Predictions:")
print(f"  {'─'*70}")
print(f"  {'Case':<6} {'Type':<12} {'Category':<18} {'Court':<18} {'Priority':<12} {'Duration'}")
print(f"  {'─'*70}")
for i, case in enumerate(test_cases, 1):
    prio, dur = predict_new_case(**case)
    print(f"  {i:<6} {case['case_type']:<12} {case['case_category']:<18} "
          f"{case['court_level']:<18} {prio:<12} ~{dur} months")
print(f"  {'─'*70}")


# ─────────────────────────────────────────────────────────────
# CELL 13 — GEMINI AI ANALYSIS
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  PHASE 5: GEMINI AI — INTELLIGENT CASE ANALYSIS")
print("=" * 60)

# ── STEP 1: Set your API key ──────────────────────────────────
# Get free API key from: https://aistudio.google.com/app/apikey
# Paste it below replacing YOUR_API_KEY_HERE

GEMINI_API_KEY = "YOUR_API_KEY_HERE"   # <── PASTE YOUR KEY HERE

genai.configure(api_key=GEMINI_API_KEY)
model_gemini = genai.GenerativeModel('gemini-1.5-flash')

def build_prompt(results_summary):
    """Build an intelligent analysis prompt for Gemini."""
    return f"""
You are an expert AI system analyzing judicial case management data for Indian courts.

Based on the following ML analysis results, provide a structured intelligence report:

=== ML RESULTS SUMMARY ===
{results_summary}

=== YOUR TASK ===
Provide a detailed analysis covering:

1. CLASSIFICATION PERFORMANCE ANALYSIS
   - Which model performed best and why?
   - What does the accuracy/F1 score tell us about real-world usability?
   - Any concerns about class imbalance or model bias?

2. REGRESSION PERFORMANCE ANALYSIS
   - Which model best predicts case duration and why?
   - What does the R² score mean for courts planning hearing schedules?
   - How reliable is the prediction for urgent cases?

3. CLUSTERING INSIGHTS
   - What do the discovered case clusters likely represent?
   - How can courts use cluster assignments for better resource allocation?

4. ANOMALY DETECTION INSIGHTS
   - What might anomalous cases represent in judicial context?
   - How should court administrators act on flagged cases?

5. RECOMMENDATIONS FOR COURTS
   - 3 actionable recommendations based on these findings
   - Potential risks of deploying this AI system in courts
   - How to improve the model further

Keep the analysis professional, data-driven, and concise (400-500 words).
"""

# Build results summary string
results_summary = f"""
DATASET: 1000 Indian judicial case records (2010-2023)
FEATURES: {len(FEATURES)} features including case type, category, court level, hearings, adjournments

CLASSIFICATION RESULTS (Priority Level Prediction):
{chr(10).join([f"  {k}: Accuracy={v['Accuracy']:.4f}, F1={v['F1 Score']:.4f}" for k, v in clf_results.items()])}
Best Model: {best_clf} (F1={clf_results[best_clf]['F1 Score']:.4f})

REGRESSION RESULTS (Case Duration Prediction):
{chr(10).join([f"  {k}: MAE={v['MAE']:.2f}, RMSE={v['RMSE']:.2f}, R²={v['R² Score']:.4f}" for k, v in reg_results.items()])}
Best Model: {best_reg} (R²={reg_results[best_reg]['R² Score']:.4f})

CLUSTERING RESULTS:
  Optimal K = {best_k} clusters
  Silhouette Score = {max(sil_scores):.4f}

ANOMALY DETECTION:
  {n_anomalies} anomalous cases detected ({n_anomalies/len(df_ml)*100:.1f}% of dataset)

SAMPLE PREDICTION:
  Criminal Murder case (High Court, 2018, 22 hearings): Priority=High, Duration≈{predict_new_case('Criminal','Murder','High Court','Maharashtra',2018,22,14,4,2,'Pending')[1]} months
"""

print("  Sending data to Gemini AI for analysis...")
print("  (This may take 10-20 seconds...)\n")

try:
    prompt   = build_prompt(results_summary)
    response = model_gemini.generate_content(prompt)
    gemini_analysis = response.text

    print("=" * 60)
    print("  GEMINI AI INTELLIGENCE REPORT")
    print("=" * 60)
    print(gemini_analysis)
    print("=" * 60)

except Exception as e:
    gemini_analysis = f"Gemini API error: {e}\nPlease check your API key."
    print(f"\n  ⚠️  {gemini_analysis}")
    print("  💡 Get a free key at: https://aistudio.google.com/app/apikey")


# ─────────────────────────────────────────────────────────────
# CELL 14 — Gemini Case-Level Explanation
# ─────────────────────────────────────────────────────────────

def explain_case_with_gemini(case_details, prediction, duration):
    """Ask Gemini to explain the prediction for a specific case."""
    prompt = f"""
You are an AI assistant helping Indian court administrators understand case prioritization decisions.

A machine learning model analyzed the following case:
- Case Type    : {case_details['case_type']}
- Category     : {case_details['case_category']}
- Court Level  : {case_details['court_level']}
- Year Filed   : {case_details['year_filed']}
- Hearings     : {case_details['num_hearings']}
- Adjournments : {case_details['num_adjournments']}
- Parties      : {case_details['num_parties']}
- Judge Changes: {case_details['judge_changes']}
- Status       : {case_details['case_status']}

ML Prediction:
- Priority Level   : {prediction}
- Estimated Duration: ~{duration} months

In 3-4 sentences, explain WHY this case received a '{prediction}' priority rating
and what courts should do next with this case. Use plain language.
"""
    try:
        response = model_gemini.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"Error: {e}"

print("\n  GEMINI CASE-LEVEL EXPLANATIONS:")
print("  " + "─" * 55)
for i, case in enumerate(test_cases, 1):
    prio, dur = predict_new_case(**case)
    explanation = explain_case_with_gemini(case, prio, dur)
    print(f"\n  Case {i}: {case['case_category']} | {case['court_level']}")
    print(f"  Priority: {prio} | Duration: ~{dur} months")
    print(f"\n  🤖 Gemini Explanation:")
    print(f"  {explanation}")
    print("  " + "─" * 55)


# ─────────────────────────────────────────────────────────────
# CELL 15 — Final Summary Dashboard
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  FINAL SUMMARY DASHBOARD")
print("=" * 60)

fig, axes = plt.subplots(2, 3, figsize=(20, 12))
fig.suptitle('AI Judicial Case System — Final Summary Dashboard',
             fontsize=16, fontweight='bold')

# 1. All Model F1 Scores
ax = axes[0, 0]
all_model_names = list(clf_results.keys())
all_f1 = [clf_results[n]['F1 Score'] for n in all_model_names]
bar_colors = ['#1D9E75' if n == best_clf else '#B4B2A9' for n in all_model_names]
bars = ax.bar(all_model_names, all_f1, color=bar_colors, edgecolor='white', linewidth=1.5)
ax.set_title('Classification — F1 Score Comparison', fontweight='bold')
ax.set_ylabel('F1 Score')
ax.set_ylim(0, 1.15)
for bar, val in zip(bars, all_f1):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f'{val:.3f}', ha='center', fontweight='bold', fontsize=10)
ax.axhline(y=0.8, color='gray', linestyle='--', linewidth=0.8, alpha=0.6)
ax.tick_params(axis='x', rotation=15)

# 2. Regression R² Score
ax = axes[0, 1]
reg_names = list(reg_results.keys())
r2_vals   = [reg_results[n]['R² Score'] for n in reg_names]
bar_colors_r = ['#1D9E75' if n == best_reg else '#B4B2A9' for n in reg_names]
bars = ax.bar(['Lin. Reg', 'RF Reg', 'SVR'], r2_vals,
              color=bar_colors_r, edgecolor='white', linewidth=1.5)
ax.set_title('Regression — R² Score Comparison', fontweight='bold')
ax.set_ylabel('R² Score')
ax.set_ylim(0, 1.1)
for bar, val in zip(bars, r2_vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f'{val:.4f}', ha='center', fontweight='bold', fontsize=10)

# 3. Feature Importance (RF Classifier)
ax = axes[0, 2]
rf_clf_model = clf_models['Random Forest'][0]
feat_imp     = rf_clf_model.feature_importances_
feat_df      = pd.DataFrame({'Feature': FEATURES, 'Importance': feat_imp})
feat_df      = feat_df.sort_values('Importance', ascending=True).tail(10)
ax.barh(feat_df['Feature'], feat_df['Importance'],
        color='#7F77DD', edgecolor='white')
ax.set_title('Top Features — RF Classifier', fontweight='bold')
ax.set_xlabel('Importance Score')

# 4. Priority Distribution in Clusters
ax = axes[1, 0]
cluster_priority = df_ml.groupby(['Cluster', 'Priority_Level']).size().unstack(fill_value=0)
cluster_priority.plot(kind='bar', ax=ax, color=[colors_priority[c] for c in cluster_priority.columns],
                       edgecolor='white', linewidth=0.8)
ax.set_title('Priority Distribution Across Clusters', fontweight='bold')
ax.set_xlabel('Cluster')
ax.set_ylabel('Number of Cases')
ax.legend(title='Priority', fontsize=9)
ax.tick_params(axis='x', rotation=0)

# 5. Case Age by Cluster (Box Plot)
ax = axes[1, 1]
cluster_data = [df_ml[df_ml['Cluster'] == c]['Case_Age_Months'].values for c in range(best_k)]
bp = ax.boxplot(cluster_data, labels=[f'C{i}' for i in range(best_k)], patch_artist=True)
for patch, color in zip(bp['boxes'], cluster_colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.75)
ax.set_title('Case Age Distribution by Cluster', fontweight='bold')
ax.set_xlabel('Cluster')
ax.set_ylabel('Case Age (Months)')

# 6. Summary Stats Card
ax = axes[1, 2]
ax.axis('off')
summary_text = [
    ('SYSTEM SUMMARY', 14, '#185FA5', True),
    ('', 11, 'black', False),
    (f'Dataset: 1,000 records | {len(FEATURES)} features', 11, 'black', False),
    (f'Train: 800 samples | Test: 200 samples', 11, 'black', False),
    ('', 10, 'black', False),
    ('── BEST MODELS ──', 11, '#185FA5', True),
    (f'Classifier : {best_clf}', 11, 'black', False),
    (f'  Accuracy : {clf_results[best_clf]["Accuracy"]:.4f}', 11, '#1D9E75', False),
    (f'  F1 Score : {clf_results[best_clf]["F1 Score"]:.4f}', 11, '#1D9E75', False),
    (f'Regressor  : {best_reg[:18]}', 11, 'black', False),
    (f'  R² Score : {reg_results[best_reg]["R² Score"]:.4f}', 11, '#1D9E75', False),
    (f'  MAE      : {reg_results[best_reg]["MAE"]:.2f} months', 11, '#1D9E75', False),
    ('', 10, 'black', False),
    ('── UNSUPERVISED ──', 11, '#185FA5', True),
    (f'K-Means Clusters  : {best_k}', 11, 'black', False),
    (f'Silhouette Score  : {max(sil_scores):.4f}', 11, '#1D9E75', False),
    (f'Anomalies Detected: {n_anomalies} cases', 11, '#E24B4A', False),
]
y_pos = 0.97
for text, size, color, bold in summary_text:
    weight = 'bold' if bold else 'normal'
    ax.text(0.05, y_pos, text, transform=ax.transAxes,
            fontsize=size, color=color, fontweight=weight, va='top')
    y_pos -= 0.058

plt.tight_layout()
plt.savefig('final_dashboard.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Final dashboard saved as 'final_dashboard.png'")


# ─────────────────────────────────────────────────────────────
# CELL 16 — Download All Outputs
# ─────────────────────────────────────────────────────────────

print("=" * 60)
print("  DOWNLOADING ALL OUTPUT FILES")
print("=" * 60)

import zipfile, os

output_files = [
    'eda_visualizations.png',
    'feature_engineering.png',
    'classification_results.png',
    'regression_results.png',
    'unsupervised_results.png',
    'final_dashboard.png',
]

# Save predictions CSV
predictions_df = df_ml[['Case_ID', 'Case_Type', 'Case_Category', 'Court_Level',
                          'Case_Age_Months', 'Priority_Level', 'Cluster', 'Is_Anomaly']].copy()
best_clf_model  = clf_models[best_clf][0]
best_reg_model  = reg_models[best_reg][0]
predictions_df['Predicted_Priority'] = le_dict['Priority_Level'].inverse_transform(
    best_clf_model.predict(X_scaled))
predictions_df['Predicted_Duration'] = np.round(best_reg_model.predict(X_scaled), 1)
predictions_df.to_csv('predictions_output.csv', index=False)
output_files.append('predictions_output.csv')

# Save Gemini analysis
with open('gemini_analysis.txt', 'w') as f:
    f.write("GEMINI AI ANALYSIS REPORT\n")
    f.write("=" * 60 + "\n")
    f.write(gemini_analysis)
output_files.append('gemini_analysis.txt')

# Zip everything
with zipfile.ZipFile('judicial_ai_outputs.zip', 'w') as zf:
    for file in output_files:
        if os.path.exists(file):
            zf.write(file)
            print(f"  ✅ Added: {file}")

print(f"\n  📦 All files zipped into: judicial_ai_outputs.zip")
print("  📥 Downloading now...")

files.download('judicial_ai_outputs.zip')

print("\n" + "=" * 60)
print("  ✅ COMPLETE! All steps done successfully.")
print("=" * 60)
print(f"""
  Summary:
  ├── Dataset          : 1,000 records, {len(FEATURES)} features
  ├── Classification   : 4 models → Best: {best_clf} (F1={clf_results[best_clf]['F1 Score']:.4f})
  ├── Regression       : 3 models → Best: {best_reg[:20]} (R²={reg_results[best_reg]['R² Score']:.4f})
  ├── Clustering       : K-Means with K={best_k} (Silhouette={max(sil_scores):.4f})
  ├── Anomalies        : {n_anomalies} flagged cases
  ├── Gemini AI        : Analysis + case-level explanations ✓
  └── Output Files     : 6 plots + predictions CSV + Gemini report
""")